bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import user_auth.urls as auth
import user_registration.urls as registration
import menu_berita.urls as berita
import menu_polling.urls as polling
import user_profile.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/registration/', permanent='true'), name='index'),
    url(r'^auth/', include(auth, namespace='auth')),
    url(r'^registration/', include(registration, namespace='registration')),
    url(r'^berita/', include(berita, namespace='berita')),
    url(r'^polling/', include(polling, namespace='polling')),
    url(r'^profile/', include(profile, namespace='profile'))
]

menu_berita/urls.py
from django.conf.urls import url
from .views import index, createnews, addnews

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^createnews', createnews, name='createnews'),
    url(r'^addnews', addnews, name='addnews')
]

menu_berita/models.py
from django.db import models

# Create your models here.

menu_berita/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.db import connection
from datetime import datetime
from collections import namedtuple

# Create your views here.
response = {}
cursor = connection.cursor()
# Create your views here.
def index(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'menuberita.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def createnews(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'addnews.html'

		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def addnews(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'confirm.html'

		now = datetime.now()
		now = now.strftime("%Y-%m-%d %H:%M:%S")

		username = request.session["username"]
		cursor.execute("SELECT id_universitas FROM NARASUMBER N WHERE N.username=%s", [username])
		res = namedtuplefetchall(cursor)
		id_univ = res[0].id_universitas

		judul = str(request.POST.get("title"))
		id_berita = str(request.POST.get("id-berita"))
		topik = str(request.POST.get("topic"))
		kata = int(str(request.POST.get("words")))
		konten = str(request.POST.get("content"))
		url = "https://bmnc.com/news/" + str(id_berita)


		cursor.execute("INSERT INTO BERITA VALUES(%s, %s, %s, %s, %s, %s, 0, %s);",
			[url,judul,topik,now,now,kata,id_univ])

		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

menu_berita/templates/addnews.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

	{% block css%}
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
 	<!-- Froala -->
    <!-- Include Editor style. -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.1/css/froala_style.min.css" rel="stylesheet" type="text/css" />
    <!-- <link href="{% static 'css/froala_style.min.css' %}" rel="stylesheet" type="text/css" /> -->
    <link href="{% static 'css/createnews.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
    {% endblock %}

    {% block title%}
	BMNC Create News
	{% endblock %}

{% block content %}
<div class="container content">
	<div class="col-xs-12 col-md-9">
		<div class="fr-view" id="preview">
			<h2>Submit Your Article</h2>
			<hr>
			<p><i>all this form fields are required</i></p>
		</div>

		<form method="post" action="{%url 'berita:addnews'%}">
			{% csrf_token %}
			<div class="form-group form-inline">
				<label class="" for="title"><b>Title </label> : </b>
				<input type="text" class="form-control" id="judul_berita" name="title">
			</div>
			<div class="form-group form-inline">
				<label class="" for="url_berita"><b>Url </label> : </b><code>https://bmnc.com/news/</code>
				<input type="text" class="form-control" id="url_berita" name="id-berita">
			</div>
			<div class="form-group form-inline">
				<label class="" for="topic"><b>Topic </label> : </b>
				<input type="text" class="form-control" id="topik_berita" name="topic">
			</div>
			<div class="form-group form-inline">
				<label class="" for="words"><b>Words </label> : </b>
				<input type="text" class="form-control" id="jumlah_kata" name="words">
			</div>
			<div class="form-group">
				<label class="" for="title"><b>Content : </label><br> </b>
				<textarea class="form-control" name="content"></textarea>
			</div>
			<button type="submit" class="btn btn-outline-danger"><a href="{%url 'berita:index'%}">Cancel</a></button>
			<button type="submit" class="btn btn-outline-dark">Submit</button>
		</form>
	</div>
	<div class="col-xs-12 col-md-3">

	</div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.1/js/froala_editor.pkgd.min.js"></script>
<script> $(function() { $('textarea').froalaEditor() }); </script>
{% endblock %}

menu_berita/templates/confirm.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block title%}
BMNC Confirmation
{% endblock %}

{% block content %}
<h1>YOU JUST CREATED NEW ARTICLE</h1>
{% endblock %}

menu_berita/templates/menuberita.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
<link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}
BMNC News
{% endblock %}

{% block content %}
	<div class="container content">
		<div class="row">
			<div class="col-xs-12 col-md-9">
				<div class="fr-view" id="preview" >
					<h2>Today's Highlight</h2>
					<hr>
				</div>
			</div>
			<div class="col-xs-12 col-md-3 new-article">
				<h2>Share Your Story!</h2>
				<p>Lorem ipsum dolor sit amet, qui ut tantas epicurei persequeris, qui odio comprehensam an. His in etiam persius. Qui mazim.</p>
				<button type="submit" class="btn btn-outline-dark"><a href="{% url 'berita:createnews' %}">Add New Article</a></button>
			</div>
		</div>
	</div>
{% endblock %}


{% block script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
{% endblock %}