bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import user_auth.urls as auth
import user_registration.urls as registration
import menu_berita.urls as berita
import menu_polling.urls as polling
import user_profile.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/registration/', permanent='true'), name='index'),
    url(r'^auth/', include(auth, namespace='auth')),
    url(r'^registration/', include(registration, namespace='registration')),
    url(r'^berita/', include(berita, namespace='berita')),
    url(r'^polling/', include(polling, namespace='polling')),
    url(r'^profile/', include(profile, namespace='profile'))
]

user_auth/urls.py
from django.conf.urls import url
from .views import login, logout

urlpatterns = [
    url(r'^login', login, name='login'),
    url(r'^logout', logout, name='logout')
]

templates/partials/footer.html
{% load staticfiles %}
{% load static %}
<footer class = "my-footer" >
   <!-- TODO Block Footer dan include footer.html -->
   <div class="row footer">
   		<div class="col-xs-4 logo">
   			<img src="{% static 'images/logo.png' %}">
   			<h6>Headquarter</h6>
   			<p>Lorem ipsum dolor sit amet, </p>
   			<p> qui ut tantas epicurei persequeris,</p>
   			<p> qui odio comprehensam an. His in etiam </p>
   			<p> persius. Qui mazim.</p>
   		</div>
   		<div class="col-xs-2 linked">
   			<h6>News</h6>
   			<p>World</p>
   			<p>US</p>
   			<p>Politics</p>
   			<p>N.Y.</p>
   			<p>Business</p>
   		</div>
   		<div class="col-xs-2 linked">
   			<h6>News</h6>
   			<p>World</p>
   			<p>US</p>
   			<p>Politics</p>
   			<p>N.Y.</p>
   			<p>Business</p>
   		</div>
   		<div class="col-xs-2 linked">
   			<h6>News</h6>
   			<p>World</p>
   			<p>US</p>
   			<p>Politics</p>
   			<p>N.Y.</p>
   			<p>Business</p>
   		</div>
   		<div class="col-xs-2 linked">
   			<h6>News</h6>
   			<p>World</p>
   			<p>US</p>
   			<p>Politics</p>
   			<p>N.Y.</p>
   			<p>Business</p>
   		</div>
   </div>

</footer>

templates/partials/header.html
{% load staticfiles %}
{% load static %}
<nav class="navbar navbar-expand-md bg-primary navbar-dark navbar-background">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="ganti-url-ini"> <!--WARNING CHANGE URL TO MAIN PAGE-->
      <img src="{% static 'images/logo.png' %}" width="150" class="d-inline-block align-top" alt="BMNC" height="50">
    </a>
    <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
      {% if header_login %}
      <ul class="nav navbar-nav">
        <li>
          <form class="form-inline" action="{% url 'auth:login' %}" method='POST'>
            {% csrf_token %}
            <label class="text-light font-weight-bold">Username:
            </label>
            <input name="field_username" type="text" class="form-control m-2" placeholder="Enter Username" required>
            <label class="text-light font-weight-bold">Password:
            </label>
            <input name="field_password" type="password" class="form-control m-2" placeholder="Password" required>
            <button type="submit" class="btn btn-success btn-md m-1">Login</button>
          </form>
        </li>
        <li>
          <a class="form-inline btn navbar-btn ml-5 text-white btn-md mt-2 m-1 register-button" href="{% url 'registration:index' %}">Register</a>
        </li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav">
        <li class="nav-item btn">
          <a class="nav-link font-weight-bold text-light" href="{% url 'profile:index' %}">Profil</a> <!--WARNING CHANGE URL-->
        </li>
        <li class="nav-item btn">
          <a class="nav-link font-weight-bold text-light" href="{% url 'berita:index' %}">Berita</a> <!--WARNING CHANGE URL-->
        </li>
        <li class="nav-item btn">
          <a class="nav-link font-weight-bold text-light" href="{% url 'polling:index' %}">Polling</a> <!--WARNING CHANGE URL-->
        </li>
        <li class="nav-item">
          <a class="btn navbar-btn text-white btn-md mt-2 btn-danger" href="{% url 'auth:logout' %}">Logout</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-danger text-center font-weight-bold" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}