bmnc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import user_auth.urls as auth
import user_registration.urls as registration
import menu_berita.urls as berita
import menu_polling.urls as polling
import user_profile.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/registration/', permanent='true'), name='index'),
    url(r'^auth/', include(auth, namespace='auth')),
    url(r'^registration/', include(registration, namespace='registration')),
    url(r'^berita/', include(berita, namespace='berita')),
    url(r'^polling/', include(polling, namespace='polling')),
    url(r'^profile/', include(profile, namespace='profile'))
]

menu_polling/urls.py
from django.conf.urls import url
from .views import index, createNewsPoll, createOwnPoll, addOwnPoll, addNewsPoll

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^createNewsPoll', createNewsPoll, name='createNewsPoll'),
    url(r'^createOwnPoll', createOwnPoll, name='createOwnPoll'),
    url(r'^confirmNewsPoll', addNewsPoll, name='addNewsPoll'),
    url(r'^confirmOwnPoll', addOwnPoll, name='addOwnPoll')
]

menu_polling/models.py
from django.db import models

# Create your models here.

menu_polling/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.db import connection
from collections import namedtuple

# Create your views here.
response = {}
cursor = connection.cursor()
# Create your views here.
def index(request):
	if "username" in request.session.keys():
		response['header_login'] = False

		cursor.execute("SELECT * FROM polling where id in  (SELECT id from polling_berita)")
		polling_berita = namedtuplefetchall(cursor)
		addUrl(polling_berita)

		cursor.execute("SELECT * FROM polling where id in  (SELECT id from polling_biasa)")
		polling_biasa = namedtuplefetchall(cursor)
		addDeskripsi(polling_biasa)

		html = 'menupoll.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def createNewsPoll(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'newspoll.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def createOwnPoll(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'ownpoll.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def addNewsPoll(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'confirmnewspoll.html'

		geturl = request.POST.get("idurl")
		starttime = str(request.POST.get("starttime"))
		endtime = str(request.POST.get("endtime"))
		question = str(request.POST.get("question"))
		ans1 = str(request.POST.get("answer1"))
		ans2 = str(request.POST.get("answer2"))

		url = "https://bmnc.com/news/" + str(geturl)
		print(starttime)
		starttime = changeFormatTime(starttime)
		endtime = changeFormatTime(endtime)

		cursor.execute("SELECT count(*) as jumlah FROM POLLING;")
		res = namedtuplefetchall(cursor)
		print(type(res), res[0].jumlah)
		id_polling = int(res[0].jumlah) + 1

		cursor.execute("INSERT INTO POLLING VALUES(%s, %s, %s, 0);", [id_polling, starttime, endtime])
		cursor.execute("INSERT INTO POLLING_BERITA VALUES(%s, %s);", [id_polling, url])
		cursor.execute("INSERT INTO RESPON VALUES(%s, %s, 0);", [id_polling, ans1])
		cursor.execute("INSERT INTO RESPON VALUES(%s, %s, 0);", [id_polling, ans2])

		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def addOwnPoll(request):
	if "username" in request.session.keys():
		response['header_login'] = False
		html = 'confirmownpoll.html'

		desc = request.POST.get("desc")
		starttime = request.POST.get("starttime")
		endtime = request.POST.get("endtime")
		question = request.POST.get("question")
		ans1 = request.POST.get("answer1")
		ans2 = request.POST.get("answer2")

		starttime = changeFormatTime(starttime)
		endtime = changeFormatTime(endtime)

		cursor.execute("SELECT count(*) as jumlah FROM POLLING;")
		res = namedtuplefetchall(cursor)
		print(type(res), res[0].jumlah)
		id_polling = int(res[0].jumlah) + 1

		cursor.execute("INSERT INTO POLLING VALUES(%s, %s, %s, 0);", [id_polling, starttime, endtime])
		cursor.execute("INSERT INTO POLLING_BIASA VALUES(%s, %s, 0);", [id_polling, desc])
		cursor.execute("INSERT INTO RESPON VALUES(%s, %s, 0);", [id_polling, ans1])
		cursor.execute("INSERT INTO RESPON VALUES(%s, %s, 0);", [id_polling, ans2])

		return render(request, html, response)
	else:
		return HttpResponseRedirect(reverse('registration:index'))

def changeFormatTime(time):
	splittedTime = time.split(" ")
	resultDate = time[0] # 12/01/2018 3:30 AM
	resultHour = time[1]
	timeHour = time[2]

	print(resultDate, resultHour, timeHour)

	if len(resultHour) == 7:
		resultHour = '0' + resultHour

	if timeHour == 'PM':
		splittedHour = resultHour.split(":")
		convertHour = int(splittedHour[0]) + 12
		resultHour = convertHour + ":" + splittedHour[1] + ":00"
	elif timeHour == 'AM':
		resultHour = "0" + resultHour + ":00"

	results = resultDate + " " + resultHour
	return results

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def addUrl(polling_berita):
	tambahan_berita = []
	for poll in polling_berita:
		cursor.execute("SELECT url_berita FROM polling_berita where id_polling = %s", [poll.id])
		tambahan_berita.append(namedtuplefetchall(cursor)[0])
	response["polling_berita"] = [polling_berita, tambahan_berita]


def addDeskripsi(polling_biasa):
	tambahan_biasa = []
	for poll in polling_biasa:
		cursor.execute("SELECT url, deskripsi FROM polling_biasa where id_polling = %s", [poll.id])
		tambahan_biasa.append(namedtuplefetchall(cursor)[0])
	response["polling_biasa"] = [polling_biasa, tambahan_biasa]

menu_polling/templates/confirmnewspoll.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block title%}
BMNC Confirmation
{% endblock %}

{% block content %}
<h1>YOU JUST CREATED NEW POLLNEWS</h1>
{% endblock %}

menu_polling/templates/confirmownpoll.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block title%}
BMNC Confirmation
{% endblock %}

{% block content %}
<h1>YOU JUST CREATED NEW OWN POLL</h1>
{% endblock %}

menu_polling/templates/menupoll.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
<link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}
Polling BMNC
{% endblock %}

{% block content %}

<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="">Polling</h1>
      </div>
    </div>
  </div>
</div>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a href="" class="active nav-link btn" data-toggle="tab" data-target="#tabone">Polling Berita</a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn" href="" data-toggle="tab" data-target="#tabtwo">Polling General</a>
          </li>
        </ul>
        <div class="tab-content mt-2">
          <div class="tab-pane fade show active" id="tabone" role="tabpanel">
            <table class="table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th class="w-50">Deskripsi</th>
                  <th>Waktu Mulai</th>
                  <th>Waktu Akhir</th>
                </tr>
              </thead>
              <tbody>
                <!-- <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/1">1</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/1">Deskripsi Polling Berita 1</a>
                  </td>
                  <td>30-4-2018 12:00:00</td>
                  <td>30-8-2018 12:00:00</td>
                </tr>
                <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/2">2</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/2">Deskripsi Polling Berita 2</a>
                  </td>
                  <td>30-4-2018 13:00:00</td>
                  <td>30-8-2018 13:00:00</td>
                </tr>
                <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/4">4</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/4">Deskripsi Polling Berita 3</a>
                  </td>
                  <td>30-4-2018 15:00:00</td>
                  <td>30-8-2018 15:00:00</td>
                </tr> -->
				{% if polling_berita and polling_berita.length > 0 %}
                {% for data in polling_berita %}
                 <tr>
                  <td>
                    <a href="{{data.1.url_berita}}">{{data.0.id}}</a>
                  </td>
                  <td>
                    <a href="{{data.1.url}}">{{data.1.url}}</a>
                  </td>
                  <td>{{data.0.polling_start}}</td>
                  <td>{{data.0.polling_end}}</td>
                </tr>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Polling Berita.
            </div>
            {% endif %}

              </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="tabtwo" role="tabpanel">
            <table class="table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th class="w-50">Deskripsi</th>
                  <th>Waktu Mulai</th>
                  <th>Waktu Akhir</th>
                </tr>
              </thead>
              <tbody>
                <!-- <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/3">3</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/3">Deskripsi Polling General 1</a>
                  </td>
                  <td>30-4-2018 14:00:00</td>
                  <td>30-8-2018 14:00:00</td>
                </tr>
                <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/5">5</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/5">Deskripsi Polling General 2</a>
                  </td>
                  <td>30-4-2018 16:00:00</td>
                  <td>30-8-2018 16:00:00</td>
                </tr>
                <tr>
                  <td>
                    <a href="https://suatuurlberita.com/berita/6">6</a>
                  </td>
                  <td>
                    <a href="https://suatuurlberita.com/berita/6">Deskripsi Polling General 3</a>
                  </td>
                  <td>30-4-2018 17:00:00</td>
                  <td>30-8-2018 17:00:00</td>
                </tr> -->
				{% if polling_biasa and polling_biasa.length > 0 %}
                {% for data in polling_biasa %}
                 <tr>
                  <td>
                    <a href="{{data.1.url}}">{{data.0.id}}</a>
                  </td>
                  <td>
                    <a href="{{data.1.url}}">{{data.1.deskripsi}}</a>
                  </td>
                  <td>{{data.0.polling_start}}</td>
                  <td>{{data.0.polling_end}}</td>
                </tr>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Polling Biasa.
            </div>
            {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-3">
        <h2>Create Your Own Polls!</h2>
        <p style="text-align: justify;">Lorem ipsum dolor sit amet, qui ut tantas epicurei persequeris, qui odio comprehensam an. His in etiam persius. Qui mazim.</p>
        <div class="related-poll row">
          <div class="col-xs-6 div-poll">
            <p id="related-poll"><i>News Related Poll</i></p>
            <button type="submit" class="btn btn-outline-dark"><a href="{%url 'polling:createNewsPoll'%}">Create</a></button>
          </div>
          <div class="col-xs-6 div-poll">
            <p id="related-poll"><i>Ordinary Poll</i></p>
            <button type="submit" class="btn btn-outline-dark"><a href="{%url 'polling:createOwnPoll'%}">Create</a></button>
          </div>
        </div>
      </div>
    </div>



  </div>
</div>
</div>
<br>
<br>
{% endblock %}

menu_polling/templates/newspoll.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
<link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/createpoll.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}
BMNC News
{% endblock %}

{% block content %}
	<div class="container content">
			<div class="col-xs-12 col-md-9">
				<div class="fr-view" id="preview">

					<h2>Create Your News Poll</h2>
					<hr>
					<p><i>all this form fields are required</i></p>
				</div>
				<form method="post" action="{%url 'polling:addNewsPoll'%}">
					{% csrf_token %}
					<div class="form-group form-inline">
						<label class="" for="basic-url"><b>Url </label> : </b><code>https://bmnc.com/news/</code>
						<input type="text" class="form-control" id="url_berita" name="idurl">
					</div>
					<div class="form-group form-inline">
						<label class="" for="title"><b>Start Time </label> : </b>
						<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
							<input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"  name="starttime" />
							<div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
								<div class="input-group-text"><i class="fa fa-calendar"></i></div>
							</div>
						</div>
					</div>
					<div class="form-group form-inline">
						<label class="" for="topic"><b>End Time </label> : </b>
						<div class="input-group date" id="datetimepicker2" data-target-input="nearest">
							<input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker2" name="endtime"/>
							<div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
								<div class="input-group-text"><i class="fa fa-calendar"></i></div>
							</div>
						</div>
					</div>
					<div class="form-group form-inline">
						<label class="" for="words"><b>Question </label> : </b>
						<input type="text" class="form-control" id="jumlah_kata" name="question">
					</div>
					<div class="form-group ">
						<label class="" for="words"><b>Answer Choice </label> : </b><br>
						<div class="input-group col-xs-12 col-md-6">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<input type="radio" aria-label="Radio button for following text input" >
								</div>
							</div>
							<input type="text" class="form-control" aria-label="Text input with radio button" name="answer1">
						</div>
						<div class="input-group col-xs-12 col-md-6">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<input type="radio" aria-label="Radio button for following text input" >
								</div>
							</div>
							<input type="text" class="form-control" aria-label="Text input with radio button" name="answer2">
						</div>
					</div>
					<button type="submit" class="btn btn-outline-danger"><a href="{%url 'polling:index'%}">Cancel</a></button>

					<button type="submit" class="btn btn-outline-dark">Submit</button>
				</form>
			</div>
			<div class="col-xs-12 col-md-3">

			</div>
		</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
<!-- moment js -->
<script type="text/javascript" src="{% static 'js/moment.js'%}"></script>

<!-- tempusdominus -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />

<script type="text/javascript">
    $(function () {
    	var today = new Date();
		var dd = today.getDate();
		var dd1 = dd+1;
		var mm = today.getMonth()+1; //January is 0!

		var yyyy = today.getFullYear();
		if(dd<10){
		    dd='0'+dd;
		}
		if(mm<10){
		    mm='0'+mm;
		}
		var today = dd+'/'+mm+'/'+yyyy;
		var tomorrow = dd1+'/'+mm+'/'+yyyy;
		console.log(tomorrow);
        $('#datetimepicker1').datetimepicker();
        $('#datetimepicker2').datetimepicker();
        $('#datetimepicker1').datetimepicker({ minDate: true, debug: true });
		$('#datetimepicker2').datetimepicker({ minDate: true, debug: true });
		$('#datetimepicker1').datetimepicker('minDate', today,  true);
		$('#datetimepicker2').datetimepicker('minDate', tomorrow,  true);
    });
</script>
{% endblock %}

menu_polling/templates/ownpoll.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
<link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/createpoll.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}
BMNC News
{% endblock %}

{% block content %}
	<div class="container content">
			<div class="col-xs-12 col-md-9">
				<div class="fr-view" id="preview">

					<h2>Create Your Own Poll</h2>
					<hr>
					<p><i>all this form fields are required</i></p>
				</div>
				<form method="post" action="{%url 'polling:addOwnPoll'%}">
					{% csrf_token %}
					<div class="form-group">
						<label class="" for="basic-url"><b>Deskripsi </label> : </b> <br>
						<textarea name="desc"></textarea>
					</div>
					<div class="form-group form-inline">
						<label class="" for="title"><b>Start Time </label> : </b>
						<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
							<input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" name="starttime" />
							<div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
								<div class="input-group-text"><i class="fa fa-calendar"></i></div>
							</div>
						</div>
					</div>
					<div class="form-group form-inline">
						<label class="" for="topic"><b>End Time </label> : </b>
						<div class="input-group date" id="datetimepicker2" data-target-input="nearest">
							<input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker2" name="endtime"/>
							<div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
								<div class="input-group-text"><i class="fa fa-calendar"></i></div>
							</div>
						</div>
					</div>
					<div class="form-group form-inline">
						<label class="" for="words"><b>Question </label> : </b>
						<input type="text" class="form-control" id="jumlah_kata" name="question">
					</div>
					<div class="form-group ">
						<label class="" for="words"><b>Answer Choice </label> : </b><br>
						<div class="input-group col-xs-12 col-md-6">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<input type="radio" aria-label="Radio button for following text input">
								</div>
							</div>
							<input type="text" class="form-control" aria-label="Text input with radio button" name="answer1">
						</div>
						<div class="input-group col-xs-12 col-md-6">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<input type="radio" aria-label="Radio button for following text input">
								</div>
							</div>
							<input type="text" class="form-control" aria-label="Text input with radio button" name="answer2">
						</div>
					</div>
					<button type="submit" class="btn btn-outline-danger"><a href="{%url 'polling:index'%}">Cancel</a></button>
					<button type="submit" class="btn btn-outline-dark">Submit</button>
				</form>
			</div>
			<div class="col-xs-12 col-md-3">

			</div>
		</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
<!-- moment js -->
<script type="text/javascript" src="{% static 'js/moment.js'%}"></script>

<!-- tempusdominus -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />

<script type="text/javascript">
    $(function () {
    	var today = new Date();
		var dd = today.getDate();
		var dd1 = dd+1;
		var mm = today.getMonth()+1; //January is 0!

		var yyyy = today.getFullYear();
		if(dd<10){
		    dd='0'+dd;
		}
		if(mm<10){
		    mm='0'+mm;
		}
		var today = dd+'/'+mm+'/'+yyyy;
		var tomorrow = dd1+'/'+mm+'/'+yyyy;
		console.log(tomorrow);
        $('#datetimepicker1').datetimepicker();
        $('#datetimepicker2').datetimepicker();
        $('#datetimepicker1').datetimepicker({ minDate: true, debug: true });
		$('#datetimepicker2').datetimepicker({ minDate: true, debug: true });
		$('#datetimepicker1').datetimepicker('minDate', today,  true);
		$('#datetimepicker2').datetimepicker('minDate', tomorrow,  true);
    });
</script>
{% endblock %}